Remove `self` from download_dataset staticmethod.
Staticmethods don't receive the `self` argument. When trying to download a dataset this happens:

```python
  File "./lib/InDomainGeneralizationBenchmark/src/lablet_generalization_benchmark/load_dataset.py", line 63, in load_data
    self.download_dataset(filename)
TypeError: download_dataset() missing 1 required positional argument: 'file_path'
```